In [1]:
import pandas as pd
df = pd.read_excel(r'C:\Users\halit.erdogan\Downloads\Ship.xlsx')

In [2]:
df

,Ship,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [3]:
df.columns = df.iloc[0,:]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [4]:
df = df.drop(df.index[0])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

In [5]:
df['Name'].value_counts()

Braund, Mr. Owen Harris                     1
Boulos, Mr. Hanna                           1
Frolicher-Stehli, Mr. Maxmillian            1
Gilinski, Mr. Eliezer                       1
Murdlin, Mr. Joseph                         1
                                           ..
Kelly, Miss. Anna Katherine "Annie Kate"    1
McCoy, Mr. Bernard                          1
Johnson, Mr. William Cahoone Jr             1
Keane, Miss. Nora A                         1
Dooley, Mr. Patrick                         1
Name: Name, Length: 891, dtype: int64

In [6]:
df = df.drop(['Name'], axis=1)

In [7]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,female,35,1,0,113803,53.1,C123,S
5,5,0,3,male,35,0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,male,27,0,0,211536,13,NaN,S
888,888,1,1,female,19,0,0,112053,30,B42,S
889,889,0,3,female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,male,26,0,0,111369,30,C148,C
891,891,0,3,male,32,0,0,370376,7.75,NaN,Q

In [8]:
df = df.drop(['PassengerId'], axis=1)

In [9]:
df['Cabin'].value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [10]:
df.isna().sum()

0
Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

### Too many NaN in Cabin --> Drop the column
### Fair amount of NaN in Age --> Assign the average age
### Only 2 Nan in Embarked --> Drop those 2 rows

In [11]:
df = df.drop(['Cabin'], axis=1)

In [12]:
df = df[df['Embarked'].notna()]

In [13]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,0,3,male,22,1,0,A/5 21171,7.25,S
2,1,1,female,38,1,0,PC 17599,71.2833,C
3,1,3,female,26,0,0,STON/O2. 3101282,7.925,S
4,1,1,female,35,1,0,113803,53.1,S
5,0,3,male,35,0,0,373450,8.05,S
...,...,...,...,...,...,...,...,...,...
887,0,2,male,27,0,0,211536,13,S
888,1,1,female,19,0,0,112053,30,S
889,0,3,female,NaN,1,2,W./C. 6607,23.45,S
890,1,1,male,26,0,0,111369,30,C
891,0,3,male,32,0,0,370376,7.75,Q

In [14]:
meanAge = int(df['Age'].mean())

In [15]:
df['Age'] = df['Age'].fillna(meanAge)

In [16]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,0,3,male,22.0,1,0,A/5 21171,7.25,S
2,1,1,female,38.0,1,0,PC 17599,71.2833,C
3,1,3,female,26.0,0,0,STON/O2. 3101282,7.925,S
4,1,1,female,35.0,1,0,113803,53.1,S
5,0,3,male,35.0,0,0,373450,8.05,S
...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.0,0,0,211536,13,S
888,1,1,female,19.0,0,0,112053,30,S
889,0,3,female,29.0,1,2,W./C. 6607,23.45,S
890,1,1,male,26.0,0,0,111369,30,C
891,0,3,male,32.0,0,0,370376,7.75,Q

In [17]:
df['Ticket'] = df['Ticket'].astype(str)

In [18]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(df['Sex'])
sex = le.transform(df['Sex']).tolist()
df['Sex'] = sex

le.fit(df['Ticket'])
ticket = le.transform(df['Ticket']).tolist()
df['Ticket'] = ticket

le.fit(df['Embarked'])
embarked = le.transform(df['Embarked']).tolist()
df['Embarked'] = embarked

In [19]:
df

0   Survived Pclass  Sex   Age SibSp Parch  Ticket     Fare  Embarked
1          0      3    1  22.0     1     0     522     7.25         2
2          1      1    0  38.0     1     0     595  71.2833         0
3          1      3    0  26.0     0     0     668    7.925         2
4          1      1    0  35.0     1     0      48     53.1         2
5          0      3    1  35.0     0     0     471     8.05         2
..       ...    ...  ...   ...   ...   ...     ...      ...       ...
887        0      2    1  27.0     0     0     100       13         2
888        1      1    0  19.0     0     0      14       30         2
889        0      3    0  29.0     1     2     674    23.45         2
890        1      1    1  26.0     0     0       8       30         0
891        0      3    1  32.0     0     0     465     7.75         1

[889 rows x 9 columns]

In [25]:
from sklearn.model_selection import train_test_split

X = df[['Pclass','Sex','Age','SibSp','Ticket','Fare','Embarked']]
y = df['Survived']

y = y.astype(bool)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [32]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import KFold, cross_val_predict, cross_val_score
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns

X_array = X.to_numpy()
y_array = y.to_numpy()

X_train_array = X_train.to_numpy()
X_test_array = X_test.to_numpy()
y_train_array = y_train.to_numpy()
y_test_array = y_test.to_numpy()

In [38]:
def scoreResults(model, x_train, x_test, y_train, y_test):

    y_train_predict = model.predict(x_train)
    y_test_predict = model.predict(x_test)

    r2_train = metrics.r2_score(y_train, y_train_predict)
    r2_test = metrics.r2_score(y_test, y_test_predict)

    mse_train = metrics.mean_squared_error(y_train, y_train_predict)
    mse_test = metrics.mean_squared_error(y_test, y_test_predict)

    return [r2_train, r2_test, mse_train, mse_test]

scores = []
lr_cv = LogisticRegression()
k = 10
cv = KFold(n_splits=k)
for train_index, test_index in cv.split(X_array):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train_array = X_array[train_index]
    X_test_array = X_array[test_index]
    y_train_array = y_array[train_index]
    y_test_array = y_array[test_index]
    
    y_train_array = y_train_array.astype(int)
    y_test_array = y_test_array.astype(int)
    
    lr_cv.fit(X_train, y_train)

    result = scoreResults(lr_cv
                          ,X_train_array
                          ,X_test_array
                          ,y_train_array
                          ,y_test_array)

    print(f"Train R2 Score: {result[0]:.4f} MSE: {result[2]:.4f}")
    print(f"Test R2 Score: {result[1]:9.4f} MSE: {result[3]:.4f}\n")
    iter += 1
    scores.append(lr_cv.score(X_test_array, y_test_array))

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: 0.1276 MSE: 0.2050
Test R2 Score:    0.2193 MSE: 0.1910

Train R2 Score: 0.1406 MSE: 0.2062
Test R2 Score:   -0.0319 MSE: 0.1798

Train R2 Score: 0.1479 MSE: 0.2013
Test R2 Score:    0.0481 MSE: 0.2247

Train R2 Score: 0.1301 MSE: 0.2025
Test R2 Score:    0.1460 MSE: 0.2135

Train R2 Score: 0.1394 MSE: 0.2025
Test R2 Score:    0.1211 MSE: 0.2135

Train R2 Score: 0.1448 MSE: 0.2025
Test R2 Score:    0.0729 MSE: 0.2135

Train R2 Score: 0.1478 MSE: 0.2000
Test R2 Score:    0.0415 MSE: 0.2360

Train R2 Score: 0.1596 MSE: 0.1988
Test R2 Score:   -0.0595 MSE: 0.2472

Train R2 Score: 0.1152 MSE: 0.2100
Test R2 Score:    0.3463 MSE: 0.1461

Train R2 Score: 0.1243 MSE: 0.2072
Test R2 Score:    0.2634 MSE: 0.1705

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [43]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

scores = []
k = 10
cv = KFold(n_splits=k)
for train_index, test_index in cv.split(X_array):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train_array = X_array[train_index]
    X_test_array = X_array[test_index]
    y_train_array = y_array[train_index]
    y_test_array = y_array[test_index]
    
    y_train_array = y_train_array.astype(int)
    y_test_array = y_test_array.astype(int)
    
    lr_cv.fit(X_train, y_train)

    result = scoreResults(dt
                          ,X_train_array
                          ,X_test_array
                          ,y_train_array
                          ,y_test_array)

    print(f"Train R2 Score: {result[0]:.4f} MSE: {result[2]:.4f}")
    print(f"Test R2 Score: {result[1]:9.4f} MSE: {result[3]:.4f}\n")
    iter += 1
    scores.append(dt.score(X_test_array, y_test_array))

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: 0.6276 MSE: 0.0875
Test R2 Score:    0.5867 MSE: 0.1011

Train R2 Score: 0.6198 MSE: 0.0912
Test R2 Score:    0.6130 MSE: 0.0674

Train R2 Score: 0.6295 MSE: 0.0875
Test R2 Score:    0.5717 MSE: 0.1011

Train R2 Score: 0.6241 MSE: 0.0875
Test R2 Score:    0.5955 MSE: 0.1011

Train R2 Score: 0.5963 MSE: 0.0950
Test R2 Score:    0.8612 MSE: 0.0337

Train R2 Score: 0.6305 MSE: 0.0875
Test R2 Score:    0.5609 MSE: 0.1011

Train R2 Score: 0.6431 MSE: 0.0838
Test R2 Score:    0.4523 MSE: 0.1348

Train R2 Score: 0.5983 MSE: 0.0950
Test R2 Score:    0.8555 MSE: 0.0337

Train R2 Score: 0.6261 MSE: 0.0887
Test R2 Score:    0.5977 MSE: 0.0899

Train R2 Score: 0.6413 MSE: 0.0849
Test R2 Score:    0.4598 MSE: 0.1250

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [44]:
from sklearn.svm import SVC

svc = SVC(kernel='rbf')

svc.fit(X_train,y_train)

scores = []
k = 10
cv = KFold(n_splits=k)
for train_index, test_index in cv.split(X_array):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train_array = X_array[train_index]
    X_test_array = X_array[test_index]
    y_train_array = y_array[train_index]
    y_test_array = y_array[test_index]
    
    y_train_array = y_train_array.astype(int)
    y_test_array = y_test_array.astype(int)
    
    lr_cv.fit(X_train, y_train)

    result = scoreResults(svc
                          ,X_train_array
                          ,X_test_array
                          ,y_train_array
                          ,y_test_array)

    print(f"Train R2 Score: {result[0]:.4f} MSE: {result[2]:.4f}")
    print(f"Test R2 Score: {result[1]:9.4f} MSE: {result[3]:.4f}\n")
    iter += 1
    scores.append(svc.score(X_test_array, y_test_array))

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: -0.3192 MSE: 0.3100
Test R2 Score:   -0.6073 MSE: 0.3933

Train R2 Score: -0.3437 MSE: 0.3225
Test R2 Score:   -0.6123 MSE: 0.2809

Train R2 Score: -0.3389 MSE: 0.3162
Test R2 Score:   -0.4278 MSE: 0.3371

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: -0.3210 MSE: 0.3075
Test R2 Score:   -0.6631 MSE: 0.4157

Train R2 Score: -0.3494 MSE: 0.3175
Test R2 Score:   -0.3415 MSE: 0.3258

Train R2 Score: -0.3462 MSE: 0.3187
Test R2 Score:   -0.3662 MSE: 0.3146

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: -0.3582 MSE: 0.3187
Test R2 Score:   -0.2779 MSE: 0.3146

Train R2 Score: -0.3743 MSE: 0.3250
Test R2 Score:   -0.1077 MSE: 0.2584

Train R2 Score: -0.3588 MSE: 0.3225
Test R2 Score:   -0.2571 MSE: 0.2809

Train R2 Score: -0.3715 MSE: 0.3246
Test R2 Score:   -0.1295 MSE: 0.2614

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [45]:
from sklearn.svm import SVC

svc = SVC(kernel='linear')

svc.fit(X_train,y_train)

scores = []
k = 10
cv = KFold(n_splits=k)
for train_index, test_index in cv.split(X_array):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train_array = X_array[train_index]
    X_test_array = X_array[test_index]
    y_train_array = y_array[train_index]
    y_test_array = y_array[test_index]
    
    y_train_array = y_train_array.astype(int)
    y_test_array = y_test_array.astype(int)
    
    lr_cv.fit(X_train, y_train)

    result = scoreResults(svc
                          ,X_train_array
                          ,X_test_array
                          ,y_train_array
                          ,y_test_array)

    print(f"Train R2 Score: {result[0]:.4f} MSE: {result[2]:.4f}")
    print(f"Test R2 Score: {result[1]:9.4f} MSE: {result[3]:.4f}\n")
    iter += 1
    scores.append(svc.score(X_test_array, y_test_array))

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: 0.0957 MSE: 0.2125
Test R2 Score:    0.2193 MSE: 0.1910

Train R2 Score: 0.1094 MSE: 0.2137
Test R2 Score:   -0.0319 MSE: 0.1798

Train R2 Score: 0.1215 MSE: 0.2075
Test R2 Score:    0.0005 MSE: 0.2360

Train R2 Score: 0.0710 MSE: 0.2162
Test R2 Score:    0.3707 MSE: 0.1573

Train R2 Score: 0.1181 MSE: 0.2075
Test R2 Score:    0.0286 MSE: 0.2360

Train R2 Score: 0.1078 MSE: 0.2112
Test R2 Score:    0.1217 MSE: 0.2022

Train R2 Score: 0.1265 MSE: 0.2050
Test R2 Score:   -0.0497 MSE: 0.2584

Train R2 Score: 0.1384 MSE: 0.2037
Test R2 Score:   -0.1558 MSE: 0.2697

Train R2 Score: 0.0836 MSE: 0.2175
Test R2 Score:    0.3463 MSE: 0.1461

Train R2 Score: 0.1190 MSE: 0.2085
Test R2 Score:    0.0179 MSE: 0.2273

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [49]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10, 10), max_iter=1000)

mlp.fit(X_train,y_train)

scores = []
k = 10
cv = KFold(n_splits=k)
for train_index, test_index in cv.split(X_array):
    # print("Train Index: ", train_index, "\n")
    # print("Test Index: ", test_index)
    X_train_array = X_array[train_index]
    X_test_array = X_array[test_index]
    y_train_array = y_array[train_index]
    y_test_array = y_array[test_index]
    
    y_train_array = y_train_array.astype(int)
    y_test_array = y_test_array.astype(int)
    
    lr_cv.fit(X_train, y_train)

    result = scoreResults(mlp
                          ,X_train_array
                          ,X_test_array
                          ,y_train_array
                          ,y_test_array)

    print(f"Train R2 Score: {result[0]:.4f} MSE: {result[2]:.4f}")
    print(f"Test R2 Score: {result[1]:9.4f} MSE: {result[3]:.4f}\n")
    iter += 1
    scores.append(mlp.score(X_test_array, y_test_array))

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Train R2 Score: -0.2554 MSE: 0.2950
Test R2 Score:   -0.5614 MSE: 0.3820

Train R2 Score: -0.2500 MSE: 0.3000
Test R2 Score:   -0.9348 MSE: 0.3371

Train R2 Score: -0.2913 MSE: 0.3050
Test R2 Score:   -0.2374 MSE: 0.2921

Train R2 Score: -0.2942 MSE: 0.3013
Test R2 Score:   -0.3035 MSE: 0.3258

Train R2 Score: -0.2909 MSE: 0.3038
Test R2 Score:   -0.2490 MSE: 0.3034

Train R2 Score: -0.3093 MSE: 0.3100
Test R2 Score:   -0.0735 MSE: 0.2472

Train R2 Score: -0.3049 MSE: 0.3063
Test R2 Score:   -0.1410 MSE: 0.2809

Train R2 Score: -0.3003 MSE: 0.3075
Test R2 Score:   -0.1558 MSE: 0.2697

Train R2 Score: -0.2745 MSE: 0.3025
Test R2 Score:   -0.4079 MSE: 0.3146

Train R2 Score: -0.2924 MSE: 0.3059
Test R2 Score:   -0.2277 MSE: 0.2841

C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\halit.erdogan\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(